/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatArea {
    }
    interface ChatBubble {
    }
    interface ChatWidget {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLChatAreaElement extends Components.ChatArea, HTMLStencilElement {
    }
    var HTMLChatAreaElement: {
        prototype: HTMLChatAreaElement;
        new (): HTMLChatAreaElement;
    };
    interface HTMLChatBubbleElement extends Components.ChatBubble, HTMLStencilElement {
    }
    var HTMLChatBubbleElement: {
        prototype: HTMLChatBubbleElement;
        new (): HTMLChatBubbleElement;
    };
    interface HTMLChatWidgetElement extends Components.ChatWidget, HTMLStencilElement {
    }
    var HTMLChatWidgetElement: {
        prototype: HTMLChatWidgetElement;
        new (): HTMLChatWidgetElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "chat-area": HTMLChatAreaElement;
        "chat-bubble": HTMLChatBubbleElement;
        "chat-widget": HTMLChatWidgetElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChatArea {
    }
    interface ChatBubble {
    }
    interface ChatWidget {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "chat-area": ChatArea;
        "chat-bubble": ChatBubble;
        "chat-widget": ChatWidget;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-area": LocalJSX.ChatArea & JSXBase.HTMLAttributes<HTMLChatAreaElement>;
            "chat-bubble": LocalJSX.ChatBubble & JSXBase.HTMLAttributes<HTMLChatBubbleElement>;
            "chat-widget": LocalJSX.ChatWidget & JSXBase.HTMLAttributes<HTMLChatWidgetElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
